### ISSUE TITLE
no released APK?

### ISSUE THREAD

**Issue by bakeiro** [12brendon34/COD-BOZ-Partially-Decompiled#1]
Hi!

Thanks for you effort, this project looks promising!

One question I have... I'm not gonna install Android studio compile everything and Blabla yo obtain the APK... Can't you just upload a link of it? That would be awesome (I can provide feedback or something if it's needed...)

Cheers!

**Comment by 12brendon34** [comment]
Alr I put one, Just grabbed whatever the last build I had.

**Comment by bakeiro** [comment]
`apk-debug` right? thanks!!
