### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by bakeiro** [12brendon34/COD-BOZ-Partially-Decompiled#2]
Hi again!

Thanks for you effort and time on this :)

I tried to run it but I couldn't, basically I get no memory error (which I have) and says that I have "0 %D free" or something like, which I believe it's an error

![Screenshot_2024-09-20-16-08-58-01_60d91696a537ccab40020926eea77592](https://github.com/user-attachments/assets/a3399487-eb3e-4255-9675-050e6a35e85f)

**Comment by bakeiro** [comment]
Wait, I need to download blackops_atitc.dz and place it somewhere in my SD right??

**Comment by 12brendon34** [comment]
![Screenshot_20240920-105931_Files](https://github.com/user-attachments/assets/e2e622ce-3f89-4ef9-bd97-22eaa6b5db06)

**Comment by AkiraKusanagi** [comment]
I know it's been awhile, but I've found a fix. You need to place the OBB files in the "OBB" folder before installing the game. Afterwards, it'll work.

**Comment by bakeiro** [comment]
yeah I saw it... solved thanks!!
